name: Add Theme
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'themes.json'

jobs:
  add-theme:
    if: startsWith(github.event.head_commit.message, 'ADD_THEME:')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add theme
        run: |
          theme_data=$(echo '${{ github.event.head_commit.message }}' | sed 's/ADD_THEME: //')
          jq --argjson new_theme "$theme_data" '.themes += [$new_theme]' themes.json > temp.json && mv temp.json themes.json
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add themes.json
          git commit -m "Added new theme" || exit 0
          git push
